# Generated by Django 3.2.5 on 2021-07-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='border',
            name='n03_003',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
